### ISSUE TITLE
What is necessary to compile ?

### ISSUE THREAD

**Issue by eogan** [zzag/dynamic-wallpaper#1]
I must be doing some basic mistake. I have opensuse leap 15 with latest KDE (same as Argon I think). So my system has Plasma framework 5.56.1

I had errors when trying to compile so I added the following packages:
gcc, gcc-c++,extra-cmake-modules

I still have errors:
"Could NOT find KF5Plasma: found neither KF5PlasmaConfig.cmake nor kf5plasma-config.cmake "

CmakeCache.txt:
//The directory containing a CMake configuration file for KF5Plasma.
KF5Plasma_DIR:PATH=KF5Plasma_DIR-NOTFOUND

//Location of the Qt5 qmake executable
QMAKE_EXECUTABLE:FILEPATH=

//The directory containing a CMake configuration file for Qt5Core.
Qt5Core_DIR:PATH=Qt5Core_DIR-NOTFOUND

I think I have all librairies but cmake didn't get the right path.
 I also tried to append
set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} /usr/lib64) to my CMakeLists.txt but it doesn't work.

Can you help with this ?

**Comment by zzag** [comment]
You probably have to install cmake, extra-cmake-modules, qt5-qtbase-devel, qt5-qtdeclarative-devel, and kf5-plasma-devel. Though take my words with a grain of salt because I'm not familiar with openSUSE or Fedora that much.

**Comment by zzag** [comment]
> I also tried to append

In general you shouldn't edit CMakeLists.txt ;-)

**Comment by eogan** [comment]
Thanks ! it compiled but I have another issue after.

I installed a big 1GB package with YAST: patterns-kde-devel_kde_frameworks

It includes extra-cmake-modules so with the compiler that's all the prerequisites for OpenSuse.

Now it looks fine !
-- Found KF5Plasma: /usr/lib64/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.56.0") 
[blah blah blah]
-- Build files have been written to: /home/eogan/Downloads/dynamic-wallpaper-1.5.1-build1/build

So I can compile but I have another error then:

Install the project...
-- Install configuration: "Release"
-- Installing: /eogan/share/dynamicwallpapers/default
CMake Error at data/cmake_install.cmake:41 (file):
  file INSTALL cannot make directory
  "/eogan/share/dynamicwallpapers/default": No such file or directory
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)
make: *** [Makefile:74: install] Error 1

I am doing my best not to edit the prefix.sh file :-)

**Comment by zzag** [comment]
This is strange. What arguments did you pass to cmake?

**Comment by eogan** [comment]
I apologize for editing the cmake command and changing /usr to /eogan :]

Compiling from the archive and not editing the cmake command works fine :-)
