### ISSUE TITLE
Settings are not displayed properly in Screen Locking panel

### ISSUE THREAD

**Issue by Schlaefer** [zzag/dynamic-wallpaper#18]
![ksnip_20191018-092641](https://user-images.githubusercontent.com/143224/67074570-adc9ae00-f189-11e9-9604-59a757178e18.png)

Other plugins with custom settings are displayed without issues.

KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.62.0
Qt Version: 5.13.1

**Comment by zzag** [comment]
Heh, I didn't know that a desktop wallpaper can be also used in kscreenlocker. That's kinda cool I guess.

**Comment by Schlaefer** [comment]
Thank you very much! :thumb:
