### ISSUE TITLE
Plugin name doesn't reflect it is brillant

### ISSUE THREAD

**Issue by eogan** [zzag/dynamic-wallpaper#2]
"Dynamic wallpaper" is an easy name to remember but that gives no clue how the plugin really works.

There is a similar function in another os and as Marcin Czachurski puts it, it is brillant:
"This idea is brilliant, because thanks to this information macOS can change images differently during Summer and during Winter. System knows where the Sun is and it will choose image which was taken in similar conditions. Brilliant."

The plugin name and description should reflect that.

**Comment by zzag** [comment]
I think the name is okay though yeah it would be great to have a bit better description. I'm just lazy... :(

**Comment by eogan** [comment]
So I propose:
"This is a brillant dynamic wallpaper for KDE Plasma. The wallpaper changes during the day to reflect the sun's position in your location."
:-)

**Comment by zzag** [comment]
Hmm, I'd like to omit brilliant part. People usually don't care how something works underneath. Also, it would sound a bit awkward. :D

**Comment by zzag** [comment]
Closing this issue due to the lack of activity.
