### ISSUE TITLE
Wallpaper creation: How to get sun's elevation and azimuth for night ?

### ISSUE THREAD

**Issue by eogan** [zzag/dynamic-wallpaper#4]
I use https://www.sunearthtools.com/fr/tools/coordinates-latlong-sunpath-map.php to get azimuth and elevation but the calculation stops at night so I miss 10 hours of night time. 
Do you know any website to calculate that ? is it something regular so I could just do some guess work ? What would be the best values fo dynamic wallpaper ?

**Comment by zzag** [comment]
Hi,

You could use
* spreadsheets from https://www.esrl.noaa.gov/gmd/grad/solcalc/calcdetails.html
* or https://keisan.casio.com/exec/system/1224682277
