### ISSUE TITLE
Support XML dynamic wallpapers

### ISSUE THREAD

**Issue by KAMiKAZOW** [zzag/dynamic-wallpaper#7]
Since many years Gnome also has a dynamic wallpaper feature. It dates back to Gnome’s 2.x days and its ones use XML definitions instead of JSON. There are many wallpaper packs using this format in the wild and tools exists that help generate those XML files.

Sample XML file for Gnome’s default wallpaper: https://github.com/GNOME/gnome-backgrounds/blob/master/backgrounds/adwaita-timed.xml.in

GUI tool: https://github.com/maoschanz/dynamic-wallpaper-editor / https://flathub.org/apps/details/com.github.maoschanz.DynamicWallpaperEditor

GLI tool: https://github.com/almet/gnome-background-generator

**Comment by zzag** [comment]
Yep, I envisioned something like this too, though I would prefer to use JSON for specifying metadata.

**Comment by zzag** [comment]
Marking as "wontfix" because this plugin uses KPackage and I don't want to introduce another code path for loading XML-based dynamic wallpapers.
